export default {
  GET_USER_DATA_ERROR: "GET_USER_DATA_ERROR",
  GET_USER_DATA_LOADING: "GET_USER_DATA_LOADING",
  GET_USER_DATA_SUCCESS: "GET_USER_DATA_SUCCESS",
  SEND_LOGIN_INFORMATION_ERROR: "SEND_LOGIN_INFORMATION_ERROR",
  SEND_LOGIN_INFORMATION_SUCCESS: "SEND_LOGIN_INFORMATION_SUCCESS",
  SEND_LOGIN_INFORMATION_LOADING: "SEND_LOGIN_INFORMATION_LOADING",
  SEND_LOGOUT_SUCCESS: "SEND_LOGOUT_SUCCESS",
  GET_USER_MESSAGES_SUCCESS: "GET_USER_MESSAGES_SUCCESS",
  GET_USER_MESSAGES_ERROR: "GET_USER_MESSAGES_ERROR",
  GET_USER_MESSAGES_LOADING: "GET_USER_MESSAGES_LOADING",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_ERROR: "REGISTER_USER_ERROR"
};
