export default {
  GET_USER_DATA_ERROR: "GET_USER_DATA_ERROR",
  GET_USER_DATA_LOADING: "GET_USER_DATA_LOADING",
  GET_USER_DATA_SUCCESS: "GET_USER_DATA_SUCCESS",
  SEND_LOGIN_INFORMATION_ERROR: "SEND_LOGIN_INFORMATION_ERROR",
  SEND_LOGIN_INFORMATION_SUCCESS: "SEND_LOGIN_INFORMATION_SUCCESS",
  SEND_LOGIN_INFORMATION_LOADING: "SEND_LOGIN_INFORMATION_LOADING",
};
